# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlIO-via-Base64
version:      0.06
version_from: lib/PerlIO/via/Base64.pm
installdirs:  site
requires:
    MIME::Base64:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.15
